### ISSUE TITLE
heatmap.ipynb example not working with Pandas version 0.20.2 and Bokeh version 0.12.5

### ISSUE THREAD

**Issue by slocoro** [bokeh/bkcharts#77]
Getting the following error when trying to run the notebook:

AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'split'

Anyone having the same issue?

**Comment by bryevdv** [comment]
Pandas introduced a breaking change. The only solution I can offer at the moment is to downgrade pandas. Please also know that `bkcharts` is effectively unmaintained at the current time. For a very high level API on top of Bokeh, I strongly recommend Holoviews (http://holoviews.org) which is already better and more capable than `bkcharts` and more importantly has an active team working on it. It will be the recommended and endorsed high level API going forward.

**Comment by slocoro** [comment]
@bryevdv thanks for your response. What version of pandas do you suggest I downgrade to?

**Comment by bryevdv** [comment]
I think anything recent before `0.20` should be fine

**Comment by slocoro** [comment]
@bryevdv Thanks a lot!
